version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build: ./docker/web
    ports: 
      - 80:80
    volumes: 
      - .:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/var/backups
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8080:80
    environment:
      PMA_HOST: "den1.mysql3.gear.host"
      PMA_USER: "staff"
      PMA_PASSWORD: "Oy025?R~rWf3"
    links:
      - mysql
