version: '3'
services:
  web:
    build: ./docker/web
    ports: 
      - 80:80
    volumes: 
      - .:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/var/backups